创建github actions
PCL-Community/prismlauncher-meta-bmclapi pull request #4
Opened 2024-05-05 10:28 UTC by Deep-Dark-Forest

2024-05-05 11:19 UTC, wuliaodexiaoluo requested changes

2024-05-05 11:19 UTC, wuliaodexiaoluo commented on .github/workflows/Sheep.yml
> +              with open('README.md', 'w') as file:
用 w+

2024-05-05 11:19 UTC, wuliaodexiaoluo commented on .github/workflows/Sheep.yml
> +              new_readme_contents = readme_contents.replace('<!-- DATA_USAGE_START -->', f"<!-- DATA_USAGE_START -->\\n本月GitHub Pages消耗数据量: {monthly_data_usage} MB")
\n

2024-05-05 11:23 UTC, wuliaodexiaoluo requested changes

2024-05-05 11:23 UTC, wuliaodexiaoluo commented on .github/workflows/Sheep.yml
> +              new_readme_contents = readme_contents.replace('<!-- DATA_USAGE_START -->', f"<!-- DATA_USAGE_START -->\\n本月GitHub Pages消耗数据量: {monthly_data_usage} MB")
这里，数据可能叠加

2024-05-05 11:32 UTC, hejiehao commented on .github/workflows/Sheep.yml
> +              git push
```suggestion
      - name: Commit and push if changed
        run: |
          rm -rf ./*
          git init -b master
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git push https://github.com/PCL-Community/prismlauncher-meta-bmclapi.git -f
```

2024-05-05 11:34 UTC, wuliaodexiaoluo commented on .github/workflows/Sheep.yml
> +              git push
6

2024-05-05 11:38 UTC, Deep-Dark-Forest commented on .github/workflows/Sheep.yml
> +              git push
草，我不小心点了commit

2024-05-05 11:48 UTC, hejiehao commented on .github/workflows/Sheep.yml
> +              git push
![E8C09FBA01E46CFC1CBF73901BA0AFDF](https://github.com/PCL-Community/prismlauncher-meta-bmclapi/assets/98140773/07f22c65-4fa3-4896-b15a-a42b01971b92)

2024-05-05 12:14 UTC, wuliaodexiaoluo approved these changes

2024-05-05 13:19 UTC, Deep-Dark-Forest commented
需要 py 大佬的审查

2024-05-06 04:47 UTC, wuliaodexiaoluo requested changes

2024-05-06 04:47 UTC, wuliaodexiaoluo commented on .github/workflows/Sheep.yml
> +              current_date = datetime.now().strftime("%Y-%m-%d")
m 是分钟 ，M 才是月份

2024-05-06 14:46 UTC, JingHai-Lingyun commented
可用了移除 Draft 标志

2024-05-06 14:59 UTC, Deep-Dark-Forest commented
我已经看不出来任何问题，需要其他人的审查

2024-05-07 00:43 UTC, wuliaodexiaoluo commented
我也看不太出来有什么问题，要不先运行一遍？

2024-05-07 01:56 UTC, wuliaodexiaoluo approved these changes
又看了一遍，没发现明显问题
等 zk 看看有无必要

2024-05-08 04:12 UTC, wuliaodexiaoluo commented
@zkitefly 看看？

2024-05-08 08:06 UTC, zkitefly commented
粗略看了下好像没什么问题？

2024-05-08 09:07 UTC, wuliaodexiaoluo commented
那 Merge?

2024-05-08 10:14 UTC, zkitefly commented
其实我在想，怎么会带这么多其他数据的？

可以试着干净点？

2024-05-09 10:54 UTC, Deep-Dark-Forest commented
> 其实我在想，怎么会带这么多其他数据的？
> 
> 可以试着干净点？

意思是，我的commit太多了？其实这些都不是我本人操作。。可能是是上游仓库有变化

2024-05-09 10:55 UTC, JingHai-Lingyun commented
有个 ci 每天都在跑更新来的

2024-05-09 12:46 UTC, zkitefly commented
快给 actio

2024-05-09 14:52 UTC, Deep-Dark-Forest commented
没事我把token改成了@HelloWFB的，不受GITHUB_TOKEN权限的影响

2024-05-10 03:10 UTC, JingHai-Lingyun commented
啊？

2024-05-10 04:22 UTC, wuliaodexiaoluo commented
内个。。。有没有一种可能，就是我们都没权限改

2024-05-10 04:23 UTC, wuliaodexiaoluo commented
三万行修改。。。。。这波遥遥领先了

2024-05-10 04:27 UTC, JingHai-Lingyun commented
> 内个。。。有没有一种可能，就是我们都没权限改

确认需要的话我放行一下

2024-05-10 10:32 UTC, Deep-Dark-Forest commented
我记得之前WFB给我发过一个截图，截图显示他也没有权限更改

2024-05-10 10:35 UTC, Deep-Dark-Forest commented
我把其他两个actions的token换成了@HelloWFB 的，看一下行不行？然后得把 @HelloWFB 添加为有write权限的Outside Collaborator，是否同意？

2024-05-10 10:52 UTC, HelloWFB commented
我现在有权在这个仓库直接写入文件了~

2024-05-10 10:53 UTC, JingHai-Lingyun commented
那我挪掉权限去（这个东西在仓库应用之前需要在组织配置里应用）

2024-05-11 00:39 UTC, wuliaodexiaoluo commented
这都改了啥啊

2024-05-12 12:27 UTC, Deep-Dark-Forest commented
@zkitefly @youzi-2333 现在能Merge了吗

2024-05-12 14:19 UTC, youzi-2333 approved these changes

2024-05-12 14:19 UTC, youzi-2333 commented on .github/workflows/Sheep.yml
> +              print("无法获取数据，请检查您的用户名、令牌或仓库名称。")
以下代码我没测试过，（主要是 SSL 有问题，后续代码也测不出）只是作为建议，加了 http 请求的 timeout 和文件编码，防止某些抽象问题，如果想要用的话……最好还是测试一下再 commit 进去

```suggestion
        run: |
          import os
          import sys
          from datetime import datetime
          import requests
          
          response = requests.get(
              f"https://api.github.com/repos/{os.environ['USERNAME']}/{os.environ['REPO_NAME']}/traffic/data",
              headers={"Authorization": f"token {os.environ['GITHUB_TOKEN']}"},
              timeout=10,
          )
          
          if not response.ok:
              print(f"Failed to fetch data usage: {response.status_code}")
              sys.exit(1)
          
          data = response.json()
          
          with open("README.md", "r", encoding="utf-8") as f:
              content = f.read()
          
          content += f"""
          ## 数据使用量更新 - {datetime.now().strftime("%Y-%M-%d")}
          本月 GitHub Pages 消耗数据量: {data['monthly_data_usage']} MB
          """
          
          with open("README.md", "w", encoding="utf-8") as file:
              file.write(content)
```

2024-05-12 14:19 UTC, youzi-2333 commented on README.md
> +本月 GitHub Pages 消耗的数据量为：
这句要不要删掉……？

2024-05-12 14:22 UTC, Deep-Dark-Forest commented on README.md
> +本月 GitHub Pages 消耗的数据量为：
如果没有这行，它头顶上那行会在首次运行此代码时被替换

2024-05-12 14:25 UTC, youzi-2333 commented on README.md
> +本月 GitHub Pages 消耗的数据量为：
哦草，我是按照我改了之后的代码看的（）就是上面那段 suggestion

2024-05-18 01:40 UTC, Deep-Dark-Forest commented
![Image_1715996368036.png](https://github.com/PCL-Community/prismlauncher-meta-bmclapi/assets/131975043/4038a0cd-b026-47ac-a23a-928134e30622)

2024-05-18 01:41 UTC, merged